feat: redis sentinel config support
eggjs/redis pull request #26
Opened 2018-12-14 10:44 UTC by JollySun

##### Checklist

- [x] `npm test` passes
- [x] tests and/or benchmarks are included
- [x] documentation is changed or added
- [x] commit message follows commit guidelines

##### Affected core subsystem(s)

##### Description of change

添加sentinel配置支持
修改了CI配置以便进行sentinel测试

2018-12-17 01:55 UTC, thonatos requested changes
测试的问题可以考虑一下，配置直接放项目的目录吧

2018-12-17 01:55 UTC, thonatos commented on .travis.yml
> +  - curl https://raw.githubusercontent.com/antirez/redis/3.0/sentinel.conf -o /tmp/sentinel.conf
配置文件放到项目内吧

2018-12-17 01:55 UTC, thonatos commented on test/redis.test.js
> +      return request(app.callback())
测试里如果有关闭`redis`实例的操作，更方便看到效果，目前这样看起来没太大问题，但是测试不全

2018-12-17 03:15 UTC, JollySun commented on test/redis.test.js
> +      return request(app.callback())
具体还需要什么测试？
我是看到github的PR活动，然后正好遇到这个问题，所以想提个PR学习一下，如果有不规范的地方还望指出。

2018-12-17 03:24 UTC, thonatos commented on test/redis.test.js
> +      return request(app.callback())
`sentinel`模式中比较重要的点在于主备切换，但是目前的测试用例里没体现出来，如果这边能加上这个，就更完善了

可以参考这边的测试用例：
- https://github.com/luin/ioredis/blob/master/test/functional/sentinel.js

2018-12-17 03:41 UTC, JollySun commented on test/redis.test.js
> +      return request(app.callback())
恩，但是用CI里起的Redis服务模拟的话，还是比较困难的吧..

2018-12-17 06:02 UTC, thonatos commented on test/redis.test.js
> +      return request(app.callback())
先把第一处改了吧，这里再考虑一下是否有比较合适的实现

2018-12-18 01:46 UTC, thonatos approved these changes

2018-12-18 02:26 UTC, merged

2018-12-18 02:28 UTC, atian25 commented
2.3.0