[WIP]feat:first implement
eggjs/redis pull request #3
Opened 2017-02-15 02:59 UTC by jtyjty99999

2017-02-15 04:27 UTC, dead-horse commented on lib/redis.js
> +    app.addSingleton('redis', createClusterClient);
感觉应该是将 cluster 和 普通的合并到一起：

```js
// config.default.js
exports.redis = {
  client: [], // cluster
  // client: {}, // 单实例
  clients: {
    instance1: {},
    instance2: [], // 可以混用
  }
}
```

2017-02-15 07:25 UTC, dead-horse requested changes

2017-02-15 07:25 UTC, dead-horse commented on config/config.default.js
> +  // client: [
```js
client: {
  cluster: true,
  nodes: [], // 叫 nodes 吧，我看 redis 的文档这样叫的 https://redis.io/topics/cluster-tutorial
}
```

2017-02-15 07:25 UTC, dead-horse commented on lib/redis.js
> +  return client;
https://github.com/eggjs/egg-mysql/blob/master/lib/mysql.js#L21 加一个心跳请求？

2017-02-15 07:25 UTC, dead-horse commented on package.json
> +    "ioredis": "*"
不要用 * 吧

2017-02-15 10:51 UTC, fengmk2 commented on appveyor.yml
> +environment:
windows 不加了，删除吧

2017-02-15 10:52 UTC, fengmk2 commented on lib/redis.js
> +
多余的空行不要。。。该写空行才写

2017-02-15 10:53 UTC, fengmk2 commented on lib/redis.js
> +  return client;
嗯，需要的，beforeStart 加个 ping 检查

2017-02-16 06:17 UTC, dead-horse commented on lib/redis.js
> +    client = new Redis.Cluster(config);
https://github.com/luin/ioredis#cluster

还支持第二个参数的，感觉应该改成 `client = new Redis.Cluster(config.nodes, config)`

2017-02-16 06:18 UTC, dead-horse commented on test/fixtures/apps/redisclusterapp/config/config.js
> +    nodes: [{
travis 上开启 cluster 模式的 redis 好像比较麻烦，搜到一个 https://github.com/Grokzen/travis-redis-cluster

2017-02-16 06:48 UTC, jtyjty99999 commented
根据 @dead-horse 提供的脚本，尝试同时依赖nodejs和python  https://stackoverflow.com/questions/18456611/is-it-possible-to-set-up-travis-to-run-tests-for-several-languages

2017-02-16 10:39 UTC, jtyjty99999 commented
@dead-horse ci过了

2017-02-17 02:31 UTC, dead-horse commented
LGTM

2017-02-17 02:31 UTC, dead-horse approved these changes

2017-02-17 03:03 UTC, merged